//
//  PickerPresenter.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/5/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickerPresentationLogic {
    func presentSomething(response: Picker.Something.Response)
}

class PickerPresenter: PickerPresentationLogic {
    weak var viewController: PickerDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Picker.Something.Response) {
        let viewModel = Picker.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
