//
//  PickerPresenter.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/5/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickerPresentationLogic {
    func presentCountries(countries: [Picker.Country.Response], selectorWorker: CountrySelectorWorker)
}

class PickerPresenter: PickerPresentationLogic {
    weak var viewController: PickerDisplayLogic?
    
    // MARK: Do something
    
    func presentCountries(countries: [Picker.Country.Response], selectorWorker: CountrySelectorWorker) {
        let countries = countries.map {
            Picker.Country.ViewModel(id: $0.id, name: $0.name, isAdded: selectorWorker.isCountryAdded(id: $0.id))
        }
        viewController?.updateCountriesTable(with: countries)
    }
    
}
