//
//  PickerInteractor.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/5/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickerSceneDelegate: class {
    func selectedCountriesDidChanged(countries: [Picker.Something.Response])
}

protocol PickerBusinessLogic {
    
}

protocol PickerDataStore {
    var delegate: PickerSceneDelegate? { get set }
}

class PickerInteractor: PickerBusinessLogic, PickerDataStore {
    var presenter: PickerPresentationLogic?
    var worker: PickerWorker?
    
    weak var delegate: PickerSceneDelegate?
    
    // MARK: Do something
    
}
