//
//  PickerModels.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/5/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Picker {
    // MARK: Use cases
    // swiftlint:disable nesting
    
    enum Country {
        struct Business: Codable {
            var id: String
            var name: String
            
            enum CodingKeys: String, CodingKey {
                case id = "alpha3Code"
                case name
            }
        }
        
        struct ViewModel {
            var id: String
            var name: String
            //var manager
            
            var isAdded: Bool {
                get {
                    true
                }
                set {
                    
                }
            }
        }
    }
}
