//
//  PickerInteractor.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/5/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickerBusinessLogic {
    func doSomething(request: Picker.Something.Request)
}

protocol PickerDataStore {
    //var name: String { get set }
}

class PickerInteractor: PickerBusinessLogic, PickerDataStore {
    var presenter: PickerPresentationLogic?
    var worker: PickerWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Picker.Something.Request) {
        worker = PickerWorker()
        worker?.doSomeWork()
        
        let response = Picker.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
