//
//  PickerRouter.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/5/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PickerRoutingLogic {
    func dismiss()
}

protocol PickerDataPassing {
    var dataStore: PickerDataStore? { get }
}

class PickerRouter: NSObject, PickerRoutingLogic, PickerDataPassing {
    weak var viewController: PickerViewController?
    var dataStore: PickerDataStore?
    
    // MARK: Navigation
    
    func dismiss() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
}
