//
//  CountrySelectorWorker.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/6/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CountrySelectorWorker {
    static let shared = CountrySelectorWorker()
     var addedCountriesIds = Set<String>()
    
    // swiftlint:disable identifier_name
    
    func isCountryAdded(id: String) -> Bool {
        addedCountriesIds.contains(id)
    }
    
    func addCountry(id: String) {
        addedCountriesIds.insert(id)
    }
    
    func removeCountry(id: String) {
        addedCountriesIds.remove(id)
    }
}
