//
//  StatusPresenter.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/3/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatusPresentationLogic {
    func presentCountries(countries: [Status.Country])
}

class StatusPresenter: StatusPresentationLogic {
    weak var viewController: StatusDisplayLogic?

    // MARK: Do something

    func presentCountries(countries: [Status.Country]) {
        viewController?.displayCountries(countries: countries)
    }
}
