//
//  StatusInteractor.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/3/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatusBusinessLogic {
    
}

protocol StatusDataStore {
    
}

class StatusInteractor: StatusBusinessLogic, StatusDataStore {
    var presenter: StatusPresentationLogic?
    var worker: StatusWorker?
}

extension StatusInteractor: PickerSceneDelegate {
    func selectedCountriesDidChanged(countries: [Picker.Something.Response]) {
//        presenter?.presentCountries(countries: countries)
    }
}
