//
//  StatusPresenter.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/3/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatusPresentationLogic {
    func presentSomething(response: Status.Something.Response)
}

class StatusPresenter: StatusPresentationLogic {
    weak var viewController: StatusDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Status.Something.Response) {
        let viewModel = Status.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
