//
//  StatusInteractor.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/3/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatusBusinessLogic {
    func updateCountriesText()
}

protocol StatusDataStore {
    
}

class StatusInteractor: StatusBusinessLogic, StatusDataStore {
    var presenter: StatusPresentationLogic?
    var countries: [Status.Country] = []
    
    private func mapCountry(_ country: Picker.Country.Response) -> Status.Country {
        Status.Country(name: country.name)
    }
    
    func updateCountriesText() {
        presenter?.presentCountries(countries: countries)
    }
}

extension StatusInteractor: PickerSceneDelegate {
    func selectedCountriesDidChanged(countries: [Picker.Country.Response]) {
        let mappedCountries = countries.map(mapCountry(_:))
        self.countries = mappedCountries
        presenter?.presentCountries(countries: mappedCountries)
    }
}
