//
//  StatusInteractor.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/3/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatusBusinessLogic
{
    func doSomething(request: Status.Something.Request)
}

protocol StatusDataStore
{
    //var name: String { get set }
}

class StatusInteractor: StatusBusinessLogic, StatusDataStore
{
    var presenter: StatusPresentationLogic?
    var worker: StatusWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Status.Something.Request)
    {
        worker = StatusWorker()
        worker?.doSomeWork()
        
        let response = Status.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
