//
//  PickerWorkerTests.swift
//  CountryPicker
//
//  Created by Pouya Yarandi on 11/6/20.
//  Copyright (c) 2020 RoundTable. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CountryPicker
import XCTest

class CountryRequestWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CountryRequestWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupPickerWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPickerWorker() {
        sut = CountryRequestWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testFetchAllCountries() {
        // Given
        let contentProvider: CountriesContentProvider = .all
        
        // When
        let fetchProcess = sut.fetchCountries(contentProvider)
        
        // Then
        fetchProcess.done { countries in
            XCTAssertFalse(countries.isEmpty)
        }
        fetchProcess.catch { error in
            XCTFail(error.asAFError.debugDescription)
        }
    }
    
    func testFetchEUCountries() {
        // Given
        let contentProvider: CountriesContentProvider = .regionalBloc(.eu)
        
        // When
        let fetchProcess = sut.fetchCountries(contentProvider)
        
        // Then
        fetchProcess.done { countries in
            XCTAssertFalse(countries.isEmpty)
        }
        fetchProcess.catch { error in
            XCTFail(error.asAFError.debugDescription)
        }
    }
}
